export const SIGN_IN_REQ = 'SIGN_IN_REQ';
export const SIGN_IN_SUCC = 'SIGN_IN_SUCC';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';


export const SIGN_UP_REQ = 'SIGN_UP_REQ';
export const SIGN_UP_SUCC = 'SIGN_UP_SUCC';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';


export const SIGN_OUT = 'SIGN_OUT';

export const UPDATE_ME_REQ = 'UPDATE_ME_REQ';
export const UPDATE_ME_SUCC = 'UPDATE_ME_SUCC';
export const UPDATE_ME_FAIL = 'UPDATE_ME_FAIL';

export const UPDATE_PASSWORD_REQ = 'UPDATE_PASSWORD_REQ';
export const UPDATE_PASSWORD_SUCC = 'UPDATE_PASSWORD_SUCC';
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL';

export const FORGOT_PASSWORD_REQ = 'FORGOT_PASSWORD_REQ';
export const FORGOT_PASSWORD_SUCC = 'FORGOT_PASSWORD_SUCC';
export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';


export const RESET_PASSWORD_REQ =  'RESET_PASSWORD_REQ';
export const RESET_PASSWORD_SUCC =  'RESET_PASSWORD_SUCC';
export const RESET_PASSWORD_FAIL =  'RESET_PASSWORD_FAIL';


export const GET_RECIPE_REQ = 'GET_RECIPE_REQ';
export const GET_RECIPE_SUCC = 'GET_RECIPE_SUCC';
export const GET_RECIPE_FAIL = 'GET_RECIPE_FAIL';

export const GET_RECIPE_BY_ID_REQ = 'GET_RECIPE_BY_ID_REQ';
export const GET_RECIPE_BY_ID_SUCC = 'GET_RECIPE_BY_ID_SUCC';
export const GET_RECIPE_BY_ID_FAIL = 'GET_RECIPE_BY_ID_FAIL';

export const GET_GATEGORY_REQ = 'GET_GATEGORY_REQ';
export const GET_GATEGORY_SUCC = 'GET_GATEGORY_SUCC';
export const GET_GATEGORY_FAIL = 'GET_GATEGORY_FAIL';

export const SEARCH_REQ = 'SEARCH_REQ';
export const SEARCH_SUCC = 'SEARCH_SUCC';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADJUST_ITEM_QTY = 'ADJUST_ITEM_QTY';
export const CLEAR_CART = 'CLEAR_CART';



export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE';
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE';


export const POST_ORDER_REQ = 'POST_ORDER_REQ';
export const POST_ORDER_SUCC = 'POST_ORDER_SUCC';
export const POST_ORDER_FAIL = 'POST_ORDER_FAIL';

export const GET_MY_ORDERS_REQ = 'GET_MY_ORDERS_REQ';
export const GET_MY_ORDERS_SUCC = 'GET_MY_ORDERS_SUCC';
export const GET_MY_ORDERS_FAIL = 'GET_MY_ORDERS_FAIL';

export const CANCEL_ORDER_REQ = 'CANCEL_ORDER_REQ';
export const CANCEL_ORDER_SUCC = 'CANCEL_ORDER_SUCC';
export const CANCEL_ORDER_FAIL = 'CANCEL_ORDER_FAIL';